server:
  port: 80
spring:
  messages:
    basename: i18n/Messages,i18n/Pages
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 配置当前要使用的数据源的操作类型
    driverClassName: com.mysql.jdbc.Driver          # 配置MySQL的驱动程序类
    url: jdbc:mysql://127.0.0.1:3306/moped          # 数据库连接地址
    username: root                                  # 数据库用户名
    password: 123456                                # 数据库连接密码
    dbcp2:                                          # 进行数据库连接池的配置
      min-idle: 5                                   # 数据库连接池的最小维持连接数
      initial-size: 5                               # 初始化提供的连接数
      max-total: 30                                 # 最大的连接数
      max-wait-millis: 10000                        # 等待连接获取的最大超时时间
    filters: stat,config,wall


mybatis:
  config-location: classpath:mybatis-config.xml         # mybatis配置文件所在路径
  mapper-locations: classpath:mapper/**/*.xml   # 所有的mapper映射文件
  map-underscore-to-camel-case: true
  log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
